# {# pkglts, readthedocs
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
{%- if 'conda' is available %}
    python: "miniconda3-4.7"
{%- else %}
    python: "3.11"
{%- endif %}

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: {{ sphinx.doc_dir }}/conf.py

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
{%- if 'conda' is available %}
conda:
  environment: conda/requirements.yml
{%- else %}
python:
  install:
   - requirements: requirements.txt
{%- endif %}

# #}
