# {# pkglts, conda.package
package:
  name: pkglts
  version: "5.4.2"
# #}

# {# pkglts, conda.src
source:
  path:
    ../
# #}

# {# pkglts, conda.req_build
requirements:
  build:
    - python >=3.6
    - setuptools
    - pytest-runner
    - coverage
    - coveralls
    - pytest
    - pytest-cov
    - pytest-mock
    - tox
# #}

# {# pkglts, conda.req_run
  run:
    - python >=3.6
    - jinja2
    - requests
    - semver
    - unidecode
# #}

build:
  number: 0
  noarch: python
  entry_points:
    - pmg = pkglts.manage_script:main
  script: python setup.py install --single-version-externally-managed --record record.txt

test:
  imports:
    - pkglts

  commands:
    - pmg --help

# {# pkglts, conda.about
about:
  summary: "Building packages with long term support"
  license: "CeCILL-C"
  license_file: LICENSE
# #}
