# {# pkglts, conda.package
package:
  name: {{ base.pkg_full_name }}
  version: "{{ version.major }}.{{ version.minor }}.{{ version.post }}"
# #}

# {# pkglts, conda.src
source:
  path:
    ../
# #}

# {# pkglts, conda.req_build
requirements:
  build:
    - python
    - setuptools
# #}

# {# pkglts, conda.req_run
  run:
    - python
{%- for dep in pysetup.requirements('install') -%}
  {%- if dep.is_conda(strict=False) %}
    - {{ dep.fmt_conda_requirement() }}
  {%- endif %}
{%- endfor %}
# #}

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

# {# pkglts, conda.about
about:
  summary: "{{ doc.description }}"
  license: "{{ license.name }}"
  license_file: LICENSE
# #}
