package:
  name: {{ base.pkg_full_name }}
  version: "{{ version.major }}.{{ version.minor }}.{{ version.post }}"

source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  summary: "{{ doc.description }}"
  license: "{{ license.name }}"
  license_file: LICENSE
